#!/bin/bash -e

export PACKAGE=fk-poseidon-testsomething
export TARGET=nm
export LOCAL_DIR=`cd .. && pwd`
export APPLICATION=testsomething
export VERSION=1.0.${BUILD_NUMBER}
export JAVA_VERSION=oracle-java8-jdk

source package/common-functions.sh
source package/make-helpers.sh

[ -z "$LOCAL_DIR" ] && die "No base dir specified"
[ ! -d "$LOCAL_DIR" ] && die "$LOCAL_DIR does not exist"

export PAC_GID=3510
export PAC_GROUP=fk-poseidon

export PAC_UID=3511
export PAC_USER=fk-poseidon-testsomething

git submodule update

cd $LOCAL_DIR

log "Copying environment properties" && copyEnvProperties common state-manager proc

log "MVN Build"

log "Creating DEB Directories" && createDirectories
log "Copying Files to DEB directory" && copyToDebDir testsomething api
log "Making DEBIAN readable" && chmod -R 755 $DEB_DIR/DEBIAN
log "Replacing placeholders" && replaceAllPlaceholders testsomething

echo "Done"
